### ISSUE TITLE
output segmentations do not match input

### ISSUE THREAD

**Issue by neuronflow** [BrainLesion/AURORA#24]
see discussion on slack:
```
I had some problems open it in ITK-Snap as the output segmentation is not aligned with the input. Did you save it with the save affine matrix?

```

Probably, the nifti header is ignored when saving?

https://github.com/BrainLesion/auxiliary/blob/9eac29c9957fc0419c7d9f66b407e397aa64b113/auxiliary/nifti/io.py#L10

this might be useful. We also have to think how we deal with this when saving numpy arrays. Should they include the headers rotations?

**Comment by MarcelRosier** [comment]
I can't reproduce this. The affine/ header are not ignored. We only use default values for NumPy inputs, but use the same as the input for Nifiti, see here: https://github.com/BrainLesion/AURORA/blob/main/brainles_aurora/inferer/inferer.py#L356

Based on my minimal medical understanding, it looks right on my available test data:
![image](https://github.com/BrainLesion/AURORA/assets/32431395/9500113c-f0c9-4ecc-be72-47103da85bb2)

If you can make the data available for me, I can try to reproduce and hopefully fix the issue.

**Comment by jonasw247** [comment]
I tested again a bit, and I couldn't reproduce either... I remember that last time several values were of for example the qoffset_x was positive/negative for segmentation/t1 image. 
![image](https://github.com/BrainLesion/AURORA/assets/13008145/8c1eb9a2-69ab-47cd-b4ec-bf98e3775e24)
So might have been some reading problem with ITK snap

**Comment by MarcelRosier** [comment]
ok, in that case i'll close. please reopen if the issues occurs again

**Comment by neuronflow** [comment]
sweet thanks for reporting back :) @jonasw247
