### ISSUE TITLE
[feature request] we need issue templates to get more meaningful issues

### ISSUE THREAD

**Issue by neuronflow** [BrainLesion/AURORA#47]
Also see:
https://github.com/BrainLesion/tutorials/issues/40

**Comment by evamariie** [comment]
Meanwhile, we do have issue templates, see: https://github.com/BrainLesion/tutorials/tree/main/.github/ISSUE_TEMPLATE
@neuronflow: I think this issue can be closed

**Comment by neuronflow** [comment]
@evamariie no this needs to be implemented for this repository :)

see what happens if you create an issue here for example:
https://github.com/BrainLesion/preprocessing/issues
