### ISSUE TITLE
readthedocs (infer method)

### ISSUE THREAD

**Issue by evamariie** [BrainLesion/AURORA#48]
Can you please write some more details for the Inferer class method infer in readthedocs? 
@MarcelRosier

**Comment by neuronflow** [comment]
@evamariie readthedocs is auto-generated from our code and documentation. However, I agree there seems to be a bug in the inclusion of our infer method.

**Comment by MarcelRosier** [comment]
good catch, made a mistake when adding the citation reminder. thanks!
